import keyMirror from 'keymirror';

export default keyMirror({
    REQUEST_NEWEST_IMAGES_LIST: null,
    NEWEST_IMAGES_LIST_LOADED: null,
    REQUEST_CATEGORIES_LIST: null,
    CATEGORIES_LIST_LOADED: null,
    REQUEST_USER_INFO: null,
    USER_CHANGED: null,
    USER_CHANGED_FAILED: null,
    ADD_IMAGE: null,
    REQUEST_CATEGORIES_IMAGES_LIST: null,
    CATEGORIES_IMAGES_LIST_LOADED: null,
    ADD_USER: null,
    NAVIGATE_TO_INDEX: null,
    REGISTER_FAILED: null,
    LOGOUT: null,
    REQUEST_GEAR_LIST: null,
    GEAR_LIST: null,
    REQUEST_USER_IMAGES_LIST: null,
    USER_IMAGES_LIST_LOADED: null,
    REQUEST_USER_LIST: null,
    USER_LIST_LOADED: null,
    USER_LIST_FAILED: null,
    DELETE_USER: null,
    DELETE_USER_FAILURE: null,
    UPDATE_GROUP: null,
    UPDATE_GROUP_FAILURE: null,
    DELETE_CATEGORY: null,
    DELETE_CATEGORY_FAILURE: null,
    UPDATE_CATEGORY_IMAGE: null,
    ADD_CATEGORY: null,
    ADD_CATEGORY_FAILED: null
});
